import type { Post } from "../posts";

const u = (id: string) => `https://images.unsplash.com/${id}?w=1600&q=75&auto=format&fit=crop`;

export const posts: Post[] = [
  {
    slug: "business-os-vs-erp",
    title: "The Business Operating System: A Modern Alternative to Traditional ERP",
    excerpt: "Why ERP systems feel so heavy for small and mid-sized companies, and how the idea of a “business operating system” changes the way a company is run from the ground up.",
    category: "Business Management",
    date: "2026-09-20",
    author: "Rayash Al-Bureihi",
    cover: u("photo-1551288049-bebda4e38f71"),
    featured: true,
    body: [
      { t: "p", v: "For decades, the default answer for any company that wanted to get organized was an ERP system: a massive piece of software covering accounting, inventory, HR, and procurement. Yet many of the companies that bought these systems still run their day on Excel and WhatsApp. The problem isn’t the companies — it’s the idea itself." },
      { t: "h2", id: "why-erp-fails", v: "Why do traditional ERP systems fall short?" },
      { t: "p", v: "ERP systems were originally designed for large enterprises with siloed departments and fixed procedures. Move them into a mid-sized company or a fast-growing store, and the gap between what the system offers and what the team actually needs becomes obvious." },
      { t: "list", v: ["Long, expensive implementations that take months before anyone sees value.", "Complex interfaces that push employees back to their spreadsheets.", "Separate modules that don’t talk to each other without extra customization.", "Every small tweak requires a consultant, a developer, and a new budget."] },
      { t: "h2", id: "what-is-business-os", v: "What is a “business operating system”?" },
      { t: "p", v: "A business operating system starts from a different question: what actually happens in your company every day? An order comes in, a task gets assigned, an expense gets approved, an employee clocks in. Instead of separate software for each department, all of these events run through one connected system — where managers see the full picture and each employee sees only what’s relevant to them." },
      { t: "quote", v: "The core difference: ERP records what happened. A business operating system helps you manage what’s happening right now." },
      { t: "h2", id: "differences", v: "The practical differences you’ll notice" },
      { t: "list", v: ["Connected data: an online order automatically updates inventory, posts to finance, and appears in the customer’s profile.", "A fast start: switch on the modules you need today and add more as you grow.", "An interface your team will actually use, on desktop and mobile.", "Clear permissions for every role instead of one shared password."] },
      { t: "h2", id: "how-to-start", v: "How do you know your company is ready to make the switch?" },
      { t: "p", v: "If your team asks “where’s the latest version of that file?” more than once a week, or you only learn last month’s profit days after it ends, your company has outgrown spreadsheets. Start by mapping your most frequent processes, then choose a system that connects them from day one." },
      { t: "p", v: "We built AzmSmart around exactly this idea: an intelligent system that brings sales, inventory, customers, finance, and HR together in one place, for companies and stores that want to be run with clarity." },
    ],
  },
  {
    slug: "landing-page-is-not-a-mini-site",
    title: "A Landing Page Is Not a Mini Website",
    excerpt: "The most common mistake we see in ad campaigns: a landing page crammed with links and sections. Here’s what makes a landing page actually convert.",
    category: "Digital Marketing",
    date: "2026-09-12",
    author: "RVIOS Team",
    cover: u("photo-1460925895917-afdab827c52f"),
    body: [
      { t: "p", v: "You pay for every visitor your ad brings in. That makes every extra link on your landing page an exit you’ve paid for. A website introduces the whole company; a landing page has a single job — getting the visitor to take one specific action." },
      { t: "h2", id: "one-goal", v: "One goal, one button" },
      { t: "p", v: "Before you design anything, finish this sentence: “I want the visitor to ___.” If it takes more than one verb to complete it, you need more than one page." },
      { t: "h2", id: "anatomy", v: "Anatomy of a high-converting landing page" },
      { t: "list", v: ["A headline that mirrors the ad’s promise almost word for word.", "A quick answer to “what’s in it for me?” before “who are you?”", "Real proof: testimonials, client logos, verifiable numbers.", "A short form or a single WhatsApp button, repeated where it makes sense.", "Fast load times on mobile, because that’s where most of your visitors are."] },
      { t: "quote", v: "Every extra form field costs you conversions. Ask only for what you need right now." },
      { t: "h2", id: "measure", v: "Measure before you judge" },
      { t: "p", v: "Connect the page to your tracking tools from day one, and test two versions of the headline or button. A decision based on one week of data beats months of guesswork." },
    ],
  },
  {
    slug: "website-care-after-launch",
    title: "Your Website Doesn’t End on Launch Day",
    excerpt: "Why websites slow down and break months after launch — and what real website care actually involves.",
    category: "Web Development",
    date: "2026-09-05",
    author: "RVIOS Team",
    cover: u("photo-1558494949-ef010cbdcc31"),
    body: [
      { t: "p", v: "Launch day is the happiest day in any website’s life — and the most deceptive. From then on, the technology starts to age, new security vulnerabilities emerge, search engine requirements shift, and content piles up without structure." },
      { t: "h2", id: "signs", v: "Signs your website needs attention" },
      { t: "list", v: ["It’s slower than it was on launch day.", "You don’t know when the last backup was taken.", "You’re afraid to change anything in case something else breaks.", "Its search rankings are slipping for no obvious reason."] },
      { t: "h2", id: "what-care-means", v: "What does website care really mean?" },
      { t: "p", v: "It isn’t just “maintenance on request.” Real care is an ongoing process: uptime and performance monitoring, regular security updates, tested backups, and small monthly improvements that add up to a big difference." },
      { t: "quote", v: "A backup you’ve never tried to restore isn’t a backup — it’s a wish." },
      { t: "h2", id: "grow", v: "From maintenance to growth" },
      { t: "p", v: "Once your website is stable, care time becomes development time: a new page for a campaign, an integration with your sales system, or an improved checkout journey based on how visitors actually behave." },
    ],
  },
  {
    slug: "sell-online-via-whatsapp",
    title: "Start Selling Online Through WhatsApp: A Practical Guide for Merchants",
    excerpt: "You don’t need a payment gateway or a tech team to get started. Practical steps to turn your WhatsApp chats into an organized store.",
    category: "E-commerce",
    date: "2026-08-28",
    author: "RVIOS Team",
    cover: u("photo-1556742049-0cfed4f6a45d"),
    body: [
      { t: "p", v: "Most merchants are already selling on WhatsApp: a product photo, a question about the price, then a deal. The problem is that it all gets lost in the chats — you can’t tell what sells best or who your loyal customers are." },
      { t: "h2", id: "catalog", v: "Step one: one catalog, one link" },
      { t: "p", v: "Instead of sending dozens of photos to every customer, gather your products in a simple store with a single link you can share in your status and on your pages. Customers browse and choose, and the order reaches you complete and well organized." },
      { t: "h2", id: "orders", v: "Step two: the order is recorded before the conversation" },
      { t: "list", v: ["The customer adds products to the cart, just like any online store.", "The order is recorded on your side with a number and full details.", "The conversation moves to WhatsApp to confirm payment and delivery."] },
      { t: "quote", v: "Keep the way of selling your customers already know — just add structure to it." },
      { t: "h2", id: "grow", v: "Step three: learn from your data" },
      { t: "p", v: "After just one month, you’ll know your best-selling products, your peak hours, and which customers keep coming back. That information alone will change how you buy and market. That’s exactly why we designed RVIOS StoreOS." },
    ],
  },
  {
    slug: "what-full-stack-means",
    title: "What Does It Mean for Your Website to Be Built Full-Stack?",
    excerpt: "A plain-language explainer for business owners: the difference between a brochure website and a fully integrated one, and when you need each.",
    category: "Web Development",
    date: "2026-08-18",
    author: "RVIOS Team",
    cover: u("photo-1498050108023-c5249f4df085"),
    body: [
      { t: "p", v: "You hear the word “full-stack” a lot in quotes and proposals. Put simply, it means the website is built across all of its layers — from the interface visitors see, all the way to the server, the database, and the dashboard you use to run it." },
      { t: "h2", id: "layers", v: "The three layers of a website" },
      { t: "list", v: ["Front end: the design, the interactions, and how fast pages load.", "Back end: the logic that processes orders, accounts, and permissions.", "Database: where products, customers, and orders are stored securely."] },
      { t: "h2", id: "when", v: "When do you need a full-stack website?" },
      { t: "p", v: "If your website will take orders, needs customer accounts, will have its content updated regularly, or has to integrate with other systems, you need a full-stack build. If it’s purely there to introduce your business, fast static pages may be all you need." },
      { t: "quote", v: "More important than the technology is having one team build every layer, so responsibility doesn’t get lost between a designer, a developer, and a hosting provider." },
    ],
  },
];
