import type { Service } from "../services";

export const services: Service[] = [
  {
    slug: "websites",
    n: "01",
    title: "Website Design & Development",
    label: "Websites",
    latin: "Websites",
    short: "From brand and interface to database and admin panel — a complete website, built by one team.",
    long:
      "We take your website end to end: UX and interface design that reflects your brand, then the front end, back end, database, and an admin panel you can run yourself. The result is a fast, secure, search-ready site built to grow with your business — not to be rebuilt a year from now.",
    includes: [
      "UI/UX design and an interactive prototype before development",
      "A fast, fully responsive front end",
      "Back end, database, and APIs",
      "An admin panel to manage your content",
      "SEO and page-speed optimization",
      "Arabic and English when you need both",
    ],
    stack: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL"],
    forWho: "Companies and brands that want a website that truly represents them and works as a real business tool, not just a digital brochure.",
    visual: { kind: "image", src: "/work/madar/home.webp", url: "madarwaafaq.com", caption: "Our work — Madar Waafaq" },
  },
  {
    slug: "web-systems",
    n: "02",
    title: "Systems & Web Applications",
    label: "Web Systems & Apps",
    latin: "Web Systems & Apps",
    short: "Internal systems, dashboards, and client portals, built around the way your company works.",
    long:
      "When off-the-shelf software doesn't fit, we build a system that works the way you do: order management, attendance, client portals, KPI dashboards, and automation for repetitive tasks. We start by mapping your workflow, then design roles, permissions, and reporting — and deliver a system that runs in any browser, on any device, with nothing to install.",
    includes: [
      "Workflow analysis and system architecture",
      "Multiple user roles and permissions",
      "KPI dashboards and exportable reports",
      "Third-party integrations via API",
      "Installable web app (PWA)",
      "Documentation and training for your team",
    ],
    stack: ["Next.js", "NestJS", "Supabase", "PostgreSQL", "PWA"],
    forWho: "Companies running their business on scattered spreadsheets and WhatsApp threads that need one clear system.",
    visual: { kind: "dashboard", caption: "Our products — the AzmSmart dashboard" },
  },
  {
    slug: "stores",
    n: "03",
    title: "Online Store Design & Development",
    label: "Online Stores",
    latin: "Online Stores",
    short: "A store that actually sells: seamless checkout, product and order management, with payments and shipping connected from day one.",
    long:
      "We design your store around how your customers buy, not around a template: product pages that convince, a cart and checkout with fewer steps, and a first-class mobile experience. Behind it, we build a dashboard for products, inventory, orders, and promotions, connected to payments, shipping, and WhatsApp. Need to move fast? We launch your store on our RVIOS StoreOS platform and grow it with you.",
    includes: [
      "Storefront design in your brand identity",
      "Product pages, categories, search, and filters",
      "Cart, online payments, and shipping options",
      "Admin panel for products, inventory, and orders",
      "Coupons, promotions, and abandoned-cart recovery",
      "Order sync with WhatsApp and accounting systems",
    ],
    stack: ["Next.js", "RVIOS StoreOS", "Stripe", "PostgreSQL", "WhatsApp API"],
    forWho: "Brands and merchants who want a store that represents them and sells — not a product page cloned across thousands of stores.",
    visual: { kind: "store", caption: "Our products — a store on RVIOS StoreOS" },
  },
  {
    slug: "landing-pages",
    n: "04",
    title: "Landing Page Design & Development",
    label: "Landing Pages",
    latin: "Landing Pages",
    short: "Pages built around a single goal: turning visitors into customers.",
    long:
      "A landing page isn't a mini website. We build it around one offer, one message, and one action for the visitor to take — with persuasive, content-led design, fast load times, and full tracking and ad integrations, so you know exactly what's driving results.",
    includes: [
      "Offer-focused headline and messaging",
      "Mobile-first design",
      "Lead forms connected to WhatsApp or your CRM",
      "Meta Pixel, Google Analytics, and Tag Manager",
      "Variants for A/B testing",
      "Fast turnaround to meet campaign deadlines",
    ],
    stack: ["Next.js", "Tailwind", "GA4", "Meta Pixel", "GTM"],
    forWho: "Ad campaigns, product launches, events — any offer whose results you want to measure precisely.",
    visual: { kind: "image", src: "/work/afs/home.webp", url: "afsksa.com", caption: "Our work — Ahmed Fayez Al-Shammari Est." },
  },
  {
    slug: "maintenance",
    n: "05",
    title: "Website & System Maintenance",
    label: "Maintenance & Growth",
    latin: "Maintenance & Growth",
    short: "Ongoing updates, monitoring, security, and improvements that keep your site and systems fast, secure, and growing with you.",
    long:
      "A website or system doesn't end on launch day. We monitor its performance, security, and backups, keep its technology and content up to date, and add the features your business needs as it grows. We also take over sites and systems built elsewhere — fixing issues and improving speed and experience.",
    includes: [
      "Uptime and performance monitoring",
      "Scheduled backups with tested restores",
      "Regular security and technology updates",
      "Speed and search ranking improvements",
      "New features and pages",
      "A clear monthly report of work done",
    ],
    stack: ["Vercel", "Cloudflare", "Lighthouse", "Search Console"],
    forWho: "Owners of existing websites who want a long-term technical partner instead of hunting for a developer every time something breaks.",
    visual: { kind: "image", src: "/work/tilal/home.webp", url: "tilal", caption: "Our work — Tilal Contracting", light: true },
  },
];
